/*
	html_header = html_header + "	<div class='row' style='font-size: 1.2rem;' >"; 
	html_header = html_header + "		<div class='col-1' style='padding: 0px 0px 0px 5px;'>";
	html_header = html_header + "        	<a id='nav-page-first' class='page-link' href='#'><<</a>";
	html_header = html_header + "   	</div>";
	html_header = html_header + "		<div class='col-1' style='padding: 0px 0px 0px 0px;'>";
	html_header = html_header + "        	<a id='nav-page-previous' class='page-link' href='#'><</a>";
	html_header = html_header + "   	</div>";
	html_header = html_header + "		<div class='col-auto'>";
    html_header = html_header + "      		<input type='number' id='nav-page-go' class='page-link' value='1' size='3'>";
	html_header = html_header + "   	</div>";
	html_header = html_header + "		<div class='col-auto'>";
	html_header = html_header + "		<div class='col-3' style='padding: 0px 0px 0px 0px;'>";
    html_header = html_header + "      		<input type='number' id='nav-limit-page' class='page-link'  size='5' disabled>";
	html_header = html_header + "   	</div>";
	html_header = html_header + "		<div class='col-1' style='padding: 0px 0px 0px 0px;'>";
    html_header = html_header + "      		<a class='page-link' id='nav-page-button' href='#'>Vá</a>";
	html_header = html_header + "   	</div>";
	html_header = html_header + "		<div class='col-1' style='padding: 0px 0px 0px 0px;'>";
	html_header = html_header + "        	<a id='nav-page-next' class='page-link' href='#'>></a>";
	html_header = html_header + "   	</div>";			
	html_header = html_header + "		<div class='col-1' style='padding: 0px 0px 0px 0px;'>";
	html_header = html_header + "        	<a id='nav-page-last' class='page-link' href='#'>>></a>";
	html_header = html_header + "   	</div>";
	html_header = html_header + "	</div>";
*/
    //html_header = html_header + "    	<ul class='pagination justify-content-left'>";
    //html_header = html_header + "      		<li class='page-item>";
    //html_header = html_header + "        		<a id='nav-page-first' class='page-link' href='#'>Primeirox</a>";
    //html_header = html_header + "      		</li>";
    //html_header = html_header + "      		<li class='page-item'";
    //html_header = html_header + "        		<a id='nav-page-previous' class='page-link' href='#'>Anterior</a>";
    //html_header = html_header + "      		</li>";
    //html_header = html_header + "      		<input type='text' id='nav-page-go' class='page-link' value='1' size='5'>";
    //html_header = html_header + "      		<input type='text' id='nav-limit-page' class='page-link' value='{$limit_page}' size='5' disabled>";
    //html_header = html_header + "      		<a class='page-link' id='nav-page-button' href='#'>Vá</a>";
    //html_header = html_header + "        	<li class='page-item'>";
    //html_header = html_header + "        		<a id='nav-page-next' class='page-link' href='#'>Próximo</a>";
    //html_header = html_header + "        	</li>";
    //html_header = html_header + "        	<li class='page-item'>";
    //html_header = html_header + "            	<a id='nav-page-last' class='page-link' href='#'>Ultimo</a>";
    //html_header = html_header + "        	</li>";
    //html_header = html_header + "    	</ul>";
	//html_header = html_header + "	</nav>";

    // Tabela
  	///html_header = html_header + "<div class='tab-pane fade show active p-3' id='one-" + table + "' role='tabpanel' >";
    ///html_header = html_header + "	<div id='body-grid' class='col-xs-12'></div>";  
	///html_header = html_header + "	<nav aria-label=''>";
    ///html_header = html_header + "    	<ul class='pagination justify-content-left'>";
    ///html_header = html_header + "      		<li class='page-item>";
    ///html_header = html_header + "        		<a id='nav-page-first' class='page-link' href='#'>Primeirox</a>";
    ///html_header = html_header + "      		</li>";
    ///html_header = html_header + "      		<li class='page-item'";
    ///html_header = html_header + "        		<a id='nav-page-previous' class='page-link' href='#'>Anterior</a>";
    ///html_header = html_header + "      		</li>";
    ///html_header = html_header + "      		<input type='text' id='nav-page-go' class='page-link' value='1' size='5'>";
    ///html_header = html_header + "      		<input type='text' id='nav-limit-page' class='page-link' value='{$limit_page}' size='5' disabled>";
    ///html_header = html_header + "      		<a class='page-link' id='nav-page-button' href='#'>Vá</a>";
    ///html_header = html_header + "        	<li class='page-item'>";
    ///html_header = html_header + "        		<a id='nav-page-next' class='page-link' href='#'>Próximo</a>";
    ///html_header = html_header + "        	</li>";
    ///html_header = html_header + "        	<li class='page-item'>";
    ///html_header = html_header + "            	<a id='nav-page-last' class='page-link' href='#'>Ultimo</a>";
    ///html_header = html_header + "        	</li>";
    ///html_header = html_header + "    	</ul>";
	///html_header = html_header + "	</nav>";
  	///html_header = html_header + "</div>"; 